controllers/ItemsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Items;
use app\models\Import;
use app\models\Check;
use app\models\Moving;
use app\models\Locations;
use app\models\ItemsSearch;
use app\models\MovingSearch;
use app\models\Status;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;

use kartik\mpdf\Pdf;
use \phpexcel;

#require "/vendor/phpoffice/phpexcel/Classes/PHPExcel.php";

/**
 * ItemsController implements the CRUD actions for Items model.
 */
class ItemsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'POST' ],
                ],
            ],
        ];
    }

    /**
     * Добавление предмета/оборудование если его нет
     * @param array $options
     *        string 'invent'
     *        string 'model'
     *        string 'comment'
     *        integer|NULL 'type_id'
     *        string|NULL 'typeName'
     *        string|NULL 'name'
     *        string|NULL 'os'
     *        string|NULL 'mac'
     *        string|NULL 'serial'
     *        string|NULL 'product'
     *        string|NULL 'modelnum'
     * @return integer|FALSE
     */
    public static function addIfNeed($options)
    {
        // Если указан инвентарный номер
        if (is_array($options) && isset($options[ 'invent' ]))
        {
            $item = Items::find()
                ->where([ 'like', 'invent', $options[ 'invent' ]]); // Ищем оборудование с инвентарным номером.
            // Если указан серийный номер
            if (isset($options[ 'serial' ])) {
                $item = $item->andWhere([ 'like', 'serial', $options[ 'serial' ]]); // Ищем дополнительно с серийным номером
            }
            $item = $item->all(); // Получаем все записи

            if (count($item) > 0) // Записи найдены, выводим первую совпавшую
            {
                return $item[0]->id;
            }
            // Внесённого оборудования не найдено. Добавим новую запись
            if (isset($options[ 'model' ]))
            {
                // Если указан тип предмета/оборудования
                if (isset($options[ 'typeName' ]))
                {
                    $type_id = TypesController::addIfNeed($options[ 'typeName' ]); // Найдём или добавим тип
                    // Если тип не добавили
                    if($type_id === FALSE)
                    {
                        $type_id = NULL; // сделаем его пустым
                    }
                }
                else
                {
                    // Если указан идентификатор типа, укажем его
                    $type_id = isset($options[ 'type_id' ]) ? $options[ 'type_id' ] : NULL;
                }
                // Создаём новую запись предмета/оборудования
                $item = new Items();
                $item->name        = isset($options[ 'name' ]) ? $options[ 'name' ] : NULL;       // Сетевое имя
                $item->model       = isset($options[ 'model' ]) ? $options[ 'model' ] : NULL;     // Наименование
                $item->invent      = isset($options[ 'invent' ]) ? $options[ 'invent' ] : NULL;   // Инвентарный номер
                $item->comment     = isset($options[ 'comment' ]) ? $options[ 'comment' ] : NULL; // Коментарий
                $item->type_id     = $type_id;                                                    // Идентификатор типа
                $item->os          = isset($options[ 'os' ]) ? $options[ 'os' ] : NULL;           // Операционная система
                $item->mac         = isset($options[ 'mac' ]) ? $options[ 'mac' ] : NULL;         // MAC-адрес
                $item->serial      = isset($options[ 'serial' ]) ? $options[ 'serial' ] : NULL;   // Серийный номер
                $item->product     = isset($options[ 'product' ]) ? $options[ 'product' ] : NULL; // Код оборудования
                $item->modelnumber = isset($options[ 'modelnumber' ]) ? $options[ 'modelnumber' ] : NULL; // Номер модели
                $item->checked     = false;                                                       // Не инвентризирован (требует внимания после импорта)
                // Сохраняем запись
                if ($item->validate() && $item->save())
                {
                    return $item->id; // Возвращаем идентификатор записанного оборудования
                }
            }
        }
        return FALSE;
    }

    /**
     * Формирование PDF файла для печати QR-кодов для наклеек
     * @param integer|array|null id
     * @return mixed
     */
    public function actionPrint()
    {
        if (! User::canPermission('takingInventory') ) {
            return $this->redirect(['site/index']);
        }
        // Список предметов/оборудования, если есть
        $id = Yii::$app->request->get('id');

        $models = Items::find();
        if (isset($id))
            if (is_array($id))
            {
                $models = $models->where([ 'in', 'id', $id ]); // Несколько предметов/оборудования
            } else
            {
                $models = $models->where([ 'id' => $id ]); // Один предмет/оборудование
            }
        $models = $models->all(); // Формирование списка

        $pdf = Yii::$app->pdf; // Pабота с PDF

        $pdf->methods[ 'SetHeader' ] = ''; // Yii::t('items', 'Items');
        $pdf->methods[ 'SetFooter' ] = ''; // ['{PAGENO}'];
        // Границы листа
        $pdf->marginLeft   = 5;
        $pdf->marginRight  = 5;
        $pdf->marginTop    = 9;
        $pdf->marginBottom = 15;
        // Имя файла для выгрузки, по умолчанию document.pdf
        $pdf->filename     = Yii::t('app', Yii::$app->name) . ' (' . Yii::t('items', 'Items') . ').pdf';

        // Заполнение страницы данными
        $pdf->content = $this->renderPartial('print', [ 'models' => $models ]);

        // Выгрузка PDF
        return $pdf->render();
    }

    /**
     * Процедура начала инвентаризации.
     * @return mixed
     */
    public function actionStart_checking()
    {
        // Проверка доступа для проведения инвентаризации
        if (! User::canPermission('takingInventory') ) {
            // Переход к списку предметов/оборудования, если доступ не разрешён.
            return $this->redirect(['index']);
        }
        // Запрос на получение списка идентификаторов предметов/оборудования, которые списаны
        $modelS = Moving::find()
            ->select('item_id')
            ->joinWith('status')
            ->Where([ 'ilike', Status::tableName() . '.name', 'Списано' ]);

        // Получаем список всех предметов/оборудования, кроме списанного
        $model = Items::find()
            ->select('id')
            ->innerJoin([ 'm' => $modelS ], 'not m.item_id = id')
            ->all();

        // Устанавливаем флаг непроинвентаризированных для всех предметов/оборудования из полученного списка.
        Items::updateAll([ 'checked' => false ], [ 'in', 'id', $model ]);

        // Переход к списку предметов/оборудования.
        return $this->redirect([ 'index' ]);
    }

    /**
     * Инвентаризация
     * @param string|null $qrcheck считанный QR-код
     * @return mixed
     */
     public function actionCheck()
     {
        // Проверка доступа для проведения инвентаризации
        if (! User::canPermission('takingInventory') ) {
            // Показ стартовой страницы, если доступ не разрешён.
            return $this->redirect(['site/index']);
        }

        $model = new Check();
        $message = '';
        if ($model->load(Yii::$app->request->post()))
        {
            if ((! empty($model->qrcheck)) && strpos($model->qrcheck, ',') !== false)
            {
                $keys = explode(',', $model->qrcheck);
                Items::updateAll([ 'checked' => true ], [ 'invent' => trim($keys[ 0 ]), 'serial' => trim($keys[ 1 ]) ]);
                $items = Items::find()->where([ 'invent' => trim($keys[ 0 ]), 'serial' => trim($keys[ 1 ]) ])->all();
                //$message = '[0] = "' . $keys[0] . '", [1] = "' . $keys[1] . '"<br />';
                foreach ($items as $row)
                {
                    $message .= $row->model . ' (' . $row->id . ')';
                }
                if ($message != '')
                    $message = Yii::t('items', 'Checked item(s): ') . $message;
                $model->qrcheck = '';
            }
        }
        $searchModel = new ItemsSearch();
        $dataProvider = $searchModel->noinvent($model);

        return $this->render('check', [
            'message'      => $message,
            'model'        => $model,
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
     }

    /**
     * Список всех предметов/оборудования.
     * @return mixed
     */
    public function actionIndex()
    {
        if (! User::canPermission('createRecord') ) {
            return $this->redirect(['site/index']);
        }
        $searchModel = new ItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Импорт данных из файла csv
     * Структура файла данных при выгрузке из 1С:
     * | № п/п |  | Предмет/оборудование |  |  |  |  |  |  | Инвентарный номер | Материально отвественное лицо |  |  | Место размещения | Регион/подразделение | Количество |
     * | 0     | 1| 2                    | 3| 4| 5| 6| 7| 8| 9                 |10                             |11|12|13                |14                    |15          |
     * | A     | B| C                    | D| E| F| G| H| I| J                 | K                             | L| M| N                | O                    | P          |

controllers/TypesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Types;
use app\models\TypesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;

/**
 * TypesController implements the CRUD actions for Types model.
 */
class TypesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'POST' ],
                ],
            ],
        ];
    }

    /**
     * Добавление типа, если необходимо
     * @param array $options
     *        string 'name' - наименование
     * @return integer|boolean - Идентификатор типа или FALSE в случае неудачи
     */
     public function addIfNeed($options)
     {
        if (is_array($options) && isset($options[ 'name' ]))
        {
            $type = Types::find()
                ->where([ 'like', 'name', $options[ 'name' ] ])
                ->all();
            if (count($type) > 0)
            {
                return $type[0]->id;
            }
            $type = new Types();
            $type->name = $options[ 'name' ];
            if ($type->validate() && $type->save())
            {
                return $type->id;
            }
        }
        return FALSE;
     }

    /**
     * Список всех типов предметов/оборудования.
     * @return mixed
     */
    public function actionIndex()
    {
        if (! User::canPermission('createRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $searchModel  = new TypesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Показ одного типа предмета/оборудования (не используется).
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionView($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['index']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Создание нового типа предмета/оборудования.
     * При успешном создании, происходит переход к списку всех типов предметов/оборудования.
     * @return mixed
     */
    public function actionCreate()
    {
        if (! User::canPermission('createRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = new Types();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'index', 'id' => $model->id ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Изменение существующего типа предмета/оборудования.
     * При успешном изменении, происходит переход к списку всех типов предметов/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionUpdate($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'index', 'id' => $model->id ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Удаление существующего типа предмета/оборудования.
     * При успешном удалении, происходит переход к списку всех типов предметов/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionDelete($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $this->findModel($id)->delete();

        return $this->redirect([ 'index' ]);
    }

    /**
     * Finds the Types model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Types the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Types::findOne($id)) !== null)
        {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/moving/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

use yii\jui\DatePicker;


use app\models\Status;
use app\models\Locations;
use app\models\Regions;

/* @var $this yii\web\View */
/* @var $model app\models\Moving */
/* @var $form yii\widgets\ActiveForm */


    // Создание сортированного списка для выбора состояний оборудования
    $states = ArrayHelper::map(Status::find()->orderBy('name')->all(), 'id', 'name');

    $defState = [];

    // Создание сортированного списка для выбора расположения оборудования
    $locations[ 'empty' ] = Yii::t('locations', 'Select location');
    $locArray = ArrayHelper::map(Locations::find()->joinWith('regions')->orderBy('name')->all(), 'id', 'name');
    foreach ($locArray as $key => $val)
    {
        $locArray[$key] = $val . ' (' .
            Regions::findOne([ 'id' => Locations::findOne(['id' => $key])->region_id ])->name .
            ')';
    }
    $locations = ArrayHelper::merge($locations, $locArray);
    $defLocate = [ 'options' => [ 'empty' => [ 'Disabled' => 'true' ], ]];


    // Создание сортированного списка для выбора состояний оборудования
    $states = ArrayHelper::map(Status::find()->orderBy('name')->all(), 'id', 'name');

    // Значения по умолчанию для случая создания нового

    $minDate = date('d.m.Y', strtotime('1990-01-01'));
    $maxDate = date('d.m.Y');

    if ($model->isNewRecord)
    {
        $defState    = [ 'options' => [ Status::findOne([ 'name' => 'Работает' ])->id => [ 'Selected' => 'true' ] ]];
        $defLocate   = [ 'options' => [ 'empty' => [ 'Disabled' => 'true' ], Locations::findOne([ 'name' => 'Матвейково' ])->id => [ 'Selected' => 'true' ]] ];
        $model->date = date('d.m.Y');
    }


?>

<div class="moving-form">

    <?php $form = ActiveForm::begin([
        'id' => 'MovingForm',
    ]); ?>

    <?= $form->field($model, 'date', [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
        ->widget(
            DatePicker::className(),
            [ 'language'   => 'ru',
              'dateFormat' => 'dd.MM.yyyy',
              'clientOptions' => [
              'todayHighlight' => true,
              'minDate' => $minDate,
              'maxDate' => $maxDate,
              ],
            ],
        ) ?>

    <?= $form->field($model, 'item_id')->hiddenInput()->label(false) ?>

    <?= $form->field($model,
            'state_id',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-2">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->dropDownList($states, $defState)
            ->label(Yii::t('status', 'Status')) ?>

    <?= $form->field(
            $model,
            'location_id',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-5">{input}</div><div class="col-md-2">' .
                Html::a(
                    Yii::t('locations', 'Locations'),
                    ['locations/index'],
                    ['class' => 'btn btn-primary']) .
                '</div><div class="col-md-8">{error}</div></div>'])
            ->dropDownList($locations, $defLocate)
            ->label(Yii::t('locations', 'Location'))
    ?>

    <?= $form->field($model, 'comment')->textarea([ 'rows' => 6 ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'),   [ 'class' => 'btn btn-success' ]) ?>
        <?= Html::a(           Yii::t('app', 'Cancel'), [ 'items/update', 'id' => $model->item_id ], [ 'class' => 'btn btn-primary' ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/moving/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MovingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="moving-search">

    <?php $form = ActiveForm::begin([
        'action' => [ 'index' ],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'item_id') ?>

    <?= $form->field($model, 'location_id') ?>

    <?= $form->field($model, 'state_id') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('moving', 'Search'), [ 'class' => 'btn btn-primary' ]) ?>
        <?= Html::resetButton( Yii::t('moving', 'Reset'),  [ 'class' => 'btn btn-outline-secondary' ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/moving/create.php
<?php

use yii\helpers\Html;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Moving */

if (! User::canPermission('createRecord'))
{
    return $this->redirect(['site/index']);
}
$this->title = Yii::t('moving', 'Create Moving') . ' ' .$model->items->invent . ' (' . $model->items->model . ')';
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params[ 'breadcrumbs' ][] = [ 'label' => Html::encode($model->items->invent), 'url' => [ 'items/update', 'id' => $model->item_id ]];
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="moving-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/moving/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MovingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

if (! User::canPermission('updateRecord'))
{
    return $this->redirect(['site/index']);
}
$this->title = Yii::t('moving', 'Movings');
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="moving-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('moving', 'Create Moving'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'id' => 'MovingTable',
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'columns'      => [
            [ 'class' => 'yii\grid\SerialColumn' ],

//            'id',
            [ 'attribute' => 'date',
                'value' => function($data)
                {
                    return showUrlUpdate($data->date, $data);
                },
                'format' => 'raw',
            ],
//            'item_id',
            [ 'attribute' => 'itemModel',
                'value' => function($data)
                {
                    return showUrlUpdate($data->items->invent . ' (' .$data->items->model . ')', $data);
                },
                'format' => 'raw',
            ],
//            'location_id',
            [ 'attribute' => 'locationName',
                'value' => function($data)
                {
                    return showUrlUpdate($data->locations->name, $data);
                },
                'format' => 'raw',
            ],
//            'state_id',
            [ 'attribute' => 'statusName',
                'value' => function($data)
                {
                    return showUrlUpdate($data->status->name, $data);
                },
                'format' => 'raw',
            ],
//            'comment:ntext',

            ['class' => 'yii\grid\ActionColumn', 'template' => '{delete}'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/moving/update.php
<?php

use yii\helpers\Html;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Moving */

if (! User::canPermission('updateRecord'))
{
    return $this->redirect(['index']);
}

$this->title = Yii::t('moving', 'Update Moving: {name}', [
    'name' => $model->items->invent . ' (' . $model->items->model . ') =>(' . Yii::$app->formatter->asDate($model->date, 'dd.MM.y') . ')',
]);
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params[ 'breadcrumbs' ][] = [ 'label' => Html::encode($model->items->invent), 'url' => [ 'items/update', 'id' => $model->item_id ]];
$this->params[ 'breadcrumbs' ][] = Yii::t('app', 'Update');
?>
<div class="moving-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/moving/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Moving */

if (! User::canPermission('updateRecord'))
{
    return $this->redirect(['site/index']);
}
$this->title = $model->items->invent . $model->date;
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/update', 'id' => $model->item_id ]];
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('moving', 'Movings'), 'url' => [ 'index' ]];
$this->params[ 'breadcrumbs' ][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="moving-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), [ 'update', 'id' => $model->id ], [ 'class' => 'btn btn-primary' ]) ?>
        <?= Html::a(Yii::t('app', 'Delete'), [ 'delete', 'id' => $model->id ], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'date',
            'item_id',
            'location_id',
            'state_id',
            'comment:ntext',
        ],
    ]) ?>

</div>