models/Check.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * Эта модель создана для формы items/check.
 *
 * @property string|null $qrcheck  QR-код инвентарного номера
 * @property int|null    $location Идентификатор места расположения
 * @property int|null    $region   Идентификатор региона/подразделения
 */
class Check extends Model
{
    public $qrcheck;
    public $location;
    public $region;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['qrcheck', ], 'string', 'max' => 255],
//            [['qrcheck', ], 'required' ],
            [['location', 'region'],  'integer' ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'qrcheck'      => Yii::t('items',     'Inventory QR-code'), // QR-код инвентарного номера
            'location'     => Yii::t('locations', 'Location'),          // Местоположение/размещение (идентификатор)
            'region'       => Yii::t('regions',   'Region'),            // Регион/подразделение (идентификатор)
        ];
    }
}

models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'name'       => Yii::t('contact', 'Name'),
            'email'      => Yii::t('contact', 'Email'),
            'subject'    => Yii::t('contact', 'Subject'),
            'body'       => Yii::t('contact', 'Body'),
            'verifyCode' => Yii::t('contact', 'Verification Code'),
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate())
        {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setReplyTo([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/Import.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * Этот класс модели создан для формы items/import
 *
 * @property file $filecsv Файл, содержащий данные
 */
class Import extends Model
{
    public $filecsv;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'filecsv' ], 'file', 'skipOnEmpty' => false, ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'filecsv' => Yii::t('items', 'CSV or XLS file'), // Файл csv
        ];
    }
    
    /**
     * 
     */
    public function upload()
    {
        if ($this->validate())
        {
            $this->filecsv->saveAs('upload/' . $this->filecsv->baseName . '.' . $this->filecsv->extension);
            return true;
        }
        else
        {
            if (isset($this->filecsv)) {
            $this->addError('filecsv', Yii::t('items', 'File upload is not valid'));
            } else {
            $this->addError('filecsv', Yii::t('items', 'Attribute filecsv is not set'));
            }
            return false;
        }
    }
}

models/Items.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table 'items'.
 *
 * @property int $id                    Идентификатор (неизменяемый)
// * @property int $type_id               Идентификатор типа оборудования
 * @property int $model_id              Идентификатор модели предмета/оборудования
 * @property string|null  $name         Сетевое имя оборудования
// * @property string|null  $model        Модель оборудования
 * @property string|null  $os           Операционная система
 * @property string|null  $mac          Сетевой MAC адрес
 * @property string|null  $serial       Серийный номер
// * @property string|null  $product      Код оборудования
// * @property string|null  $modelnumber  Номер модели
 * @property string|null  $invent       Инвентарный номер
 * @property boolean      $checked      Флаг прохождения инвентаризации
 * @property string|null  $statusName   Наименование состояния
 * @property string|null  $typeName     Наименование типа
 * @property string|null  $locationName Наименование места размещения
 * @property string|null  $regionName   Наименование региона/подразделения
 * @property string|null  $modelName    Наименование предмета/оборудования
 */
class Items extends \yii\db\ActiveRecord
{
    public $statusName;
    public $typeName;
    public $locationName;
    public $regionName;
    public $modelName;
    public $myMessage;
     /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%items}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'name', 'os', 'serial', 'comment' ], 'string', 'max' => 255 ],
            [[ 'mac' ],    'string', 'max' => 20 ],
            [[ 'invent' ], 'string', 'max' => 50 ],
            [[ 'model_id' ], 'integer' ],
            [[ 'checked' ], 'integer' ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'           => Yii::t('app',   'Identifier'),              // Идентификатор
            'name'         => Yii::t('items', 'Item network name'),       // Сетевое имя оборудования
            'modelName'    => Yii::t('items', 'Model'),                   // Модель
            'model_id'     => Yii::t('items', 'Model identifier'),        // Идентификатор модели
            'typeName'     => Yii::t('items', 'Item type'),               // Название типа
            'os'           => Yii::t('items', 'Operating system'),        // Операционная система
            'mac'          => Yii::t('items', 'MAC address'),             // MAC адрес
            'serial'       => Yii::t('items', 'Serial number'),           // Серийный номер
            'invent'       => Yii::t('items', 'Inventory number'),        // Инвентарный номер
            'comment'      => Yii::t('items', 'Additional Information'),  // Дополнительная информация
            'checked'      => Yii::t('items', 'Location checked'),        // Проинвентаризировано
            'statusName'   => Yii::t('items', 'State'),                   // Название состояния
            'locationName' => Yii::t('items', 'Location'),                // Название местоположения
            'regionName'   => Yii::t('items', 'Region'),                  // Название подразделения

        ];
    }

    // Получение всех перемещений предмета/оборудования
    public function getMoving()
    {
        return $this->hasMany(Moving::className(), ['item_id' => 'id']);
    }

    // Получение модели предмета/оборудования
    public function getModels()
    {
        return $this->hasOne(Models::className(), ['id' => 'model_id']);
    }

    // Получение статусов предмета/оборудования
    public function getStatus()
    {
        return $this->getMoving()->select(Status::tableName() . '.*')->joinWith('status');
    }

    // Получение места размещения предмета/оборудования
    public function getLocations()
    {
        return $this->getMoving()->select(Locations::tableName() . '.*')->joinWith('locations');
    }

    // Получение региона/подразделения размещения предмета/оборудования
    public function getRegions()
    {
        return $this->getLocations()->select(Regions::tableName() .'.*')->joinWith('regions');
    }

    // Получение типа предмета/оборудования
    public function getTypes()
    {
        return $this->getModels()->select(Types::tableName() . '.*')->joinWith('types');
    }
}

models/Locations.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table '{{%locations}}'.
 *
 * @property int $id Идентификатор места (неизменяемое)
 * @property int $region_id Идентификатор региона (подразделения)
 * @property string $name Нименование маста размещения
 * @property string $regionName Нименование региона/подразделения
 *
 * @property Items[] $items
 * @property Regions $region
 */
class Locations extends \yii\db\ActiveRecord
{

    public $regionName;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%locations}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['region_id', 'name'], 'required'],
            [['region_id'], 'default', 'value' => null],
            [['id', 'region_id'], 'integer'],
            [['name'], 'string', 'max' => 120],
            [['region_id'], 'exist', 'skipOnError' => true, 'targetClass' => Regions::className(), 'targetAttribute' => ['region_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'         => Yii::t('app',       'Identifier'),
            'region_id'  => Yii::t('locations', 'Region ID'),
            'name'       => Yii::t('locations', 'Location name'),
            'regionName' => Yii::t('regions',   'Region name'),
        ];
    }

    // Получение связанных с конкретным местом перемещений предметов/оборудования 
    public function getMoving()
    {
        return $this->hasMany(Moving::className(), ['location_id' => 'id']);
    }

    /**
     * Получение связанного оборудования с конкретным местом
     *
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->getMoving()->select(Items::tableName() . '.*')->joinWith('items');
    }

    /**
     * Получение подразделения для конкретного места
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRegions()
    {
        return $this->hasOne(Regions::className(), ['id' => 'region_id']);
    }
}

controllers/TypesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Types;
use app\models\TypesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;

/**
 * TypesController implements the CRUD actions for Types model.
 */
class TypesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'POST' ],
                ],
            ],
        ];
    }

    /**
     * Добавление типа, если необходимо
     * @param array $options
     *        string 'name' - наименование
     * @return integer|boolean - Идентификатор типа или FALSE в случае неудачи
     */
     public function addIfNeed($options)
     {
        $result = [
            'id' => FALSE,
            'error' => Yii::t('types', 'Types: key field "type" missing: ') . print_r($options, TRUE),
        ];
        if (is_array($options) && isset($options[ 'type' ]))
        {
            $model = Types::find()
                ->where([ 'like', 'name', $options[ 'type' ] ])
                ->all();
            if (count($model) > 0)
            {
                $result['id'] = $model[0]->id;
                $result['error'] = '';
            }
            else
            {
                $model = new Types();
                $model->name = $options[ 'type' ];
                if ($model->validate() && $model->save())
                {
                    $result['id'] = $model->id;
                    $result['error'] = '';
                }
                else
                {
                    $result['error'] = Yii::t('types', 'Failed to add entry "{type}": ', $options) . print_r($model->errors['name'], TRUE);
                }
            }
        }
        return $result;
     }

    /**
     * Список всех типов предметов/оборудования.
     * @return mixed
     */
    public function actionIndex()
    {
        if (! User::canPermission('createRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $searchModel  = new TypesSearch();
        if (isset(Yii::$app->request->queryParams['id'])) {
            $id = Yii::$app->request->queryParams['id'];
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            //$dataProvider->query->select(Types::tableName() . '.id');
            $pageSize = $dataProvider->pagination->pageSize;
            $dataProvider->pagination = FALSE;
            $rows = $dataProvider->getModels();
            $page = 0;
            foreach ($rows as $key => $val) {
                if ($id == $val->id) {
                    $page = ceil(($key + 1) / $pageSize);
                    break;
                }
            }
            return $this->redirect(['index', 'page' => $page]);
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Показ одного типа предмета/оборудования (не используется).
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionView($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['index']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Создание нового типа предмета/оборудования.
     * При успешном создании, происходит переход к списку всех типов предметов/оборудования.
     * @return mixed
     */
    public function actionCreate()
    {
        if (! User::canPermission('createRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = new Types();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'index', 'id' => $model->id ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Изменение существующего типа предмета/оборудования.
     * При успешном изменении, происходит переход к списку всех типов предметов/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionUpdate($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'index', 'id' => $model->id ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Удаление существующего типа предмета/оборудования.
     * При успешном удалении, происходит переход к списку всех типов предметов/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionDelete($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $this->findModel($id)->delete();

        return $this->redirect([ 'index' ]);
    }

    /**
     * Finds the Types model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Types the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Types::findOne($id)) !== null)
        {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/models/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use yii\helpers\ArrayHelper;

use app\models\Types;

/* @var $this yii\web\View */
/* @var $model app\models\Models */
/* @var $form yii\widgets\ActiveForm */

$types = ArrayHelper::map(Types::find()->orderBy('name')->all(), 'id', 'name');

?>

<div class="models-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model,
            'name',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'type_id',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-5">{input}</div><div class="col-md-2">' .
                       Html::a(Yii::t('types', 'Types'), [ 'types/index' ], [ 'class' => 'btn btn-primary' ] ) .
                       '</div><div class="col-md-8">{error}</div></div>' ])
            ->dropDownList( $types, ['prompt' => Yii::t('types', 'Select type')] ) ?>


    <?= $form->field($model,
            'product',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'modelnumber',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'),   [ 'class' => 'btn btn-success' ]) ?>
        <?= Html::a(           Yii::t('app', 'Cancel'), [ 'index' ], [ 'class' => 'btn btn-primary' ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/models/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ModelsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="models-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'type_id') ?>

    <?= $form->field($model, 'modelnum') ?>

    <?= $form->field($model, 'product') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/models/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Models */

$this->title = Yii::t('models', 'Create Model');
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('models', 'Models'), 'url' => [ 'index' ]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="models-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/models/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;

use app\models\User;
use app\models\Types;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ModelsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('models', 'Models');
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params['breadcrumbs'][] = $this->title;

$columns = [[ 'class' => 'yii\grid\SerialColumn' ]];
 // Кнопки действий {view} {update} {delete} {print}
$template = '';
$buttons = [];
if (User::canPermission('updateRecord'))
{
    // Кнопки
    $template .= ' {delete}';
    // Наименование
    array_push($columns, [ 'attribute' => 'name',
        'value' => function ($data)
        {
            return showUrlUpdate($data->name, $data);
        },
        'format' => 'raw',
    ] );
    // Тип модели
    array_push($columns, [ 'attribute' => 'typeName',
        'filter' => Html::activeDropDownList(
            $searchModel,
            'typeName',
            ArrayHelper::merge(
                [ '' => Yii::t('types', 'All types'), ],
                ArrayHelper::map(Types::find()->orderBy('name')->all(), 'name', 'name')
            ),
            [ 'class' => 'form-control', ],
        ) ,
        'value' => function ($data)
        {
            return showUrlUpdate($data->typeName, $data);
        },
        'format' => 'raw',
    ] );
    // Номер модели
    array_push($columns, [ 'attribute' => 'modelnumber',
        'value' => function ($data)
        {
            return showUrlUpdate($data->modelnumber, $data);
        },
        'format' => 'raw',
    ] );
    // Код продукта
    array_push($columns, [ 'attribute' => 'product',
        'value' => function ($data)
        {
            return showUrlUpdate($data->product, $data);
        },
        'format' => 'raw',
    ] );
    array_push($columns, [ 'class' => 'yii\grid\ActionColumn', 'template' => $template ]);
}
else
{
    array_push($columns, 'name');
    array_push($columns, [ 'attribute' => 'typeName',
        'filter' => Html::activeDropDownList(
            $searchModel,
            'typeName',
            ArrayHelper::merge(
                [ '' => Yii::t('types', 'All types'), ],
                ArrayHelper::map(Types::find()->orderBy('name')->all(), 'name', 'name')
            ),
            [ 'class' => 'form-control', ],
        ),
    ]);
    array_push($columns, 'modelnumber');
    array_push($columns, 'product');
}
?>
<div class="models-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('models', 'Create Model'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'id'           => 'ModelsTable',
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'columns'      => $columns,
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/models/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Models */

$this->title = Yii::t('models', 'Update Model: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('models', 'Models'), 'url' => [ 'index' ]];
//$this->params['breadcrumbs'][] = [ 'label' => $model->name, 'url' => [ 'view', 'id' => $model->id ]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="models-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/models/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Models */

$this->title = $model->name;
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('items', 'Items'), 'url' => [ 'items/index' ]];
$this->params['breadcrumbs'][] = [ 'label' => Yii::t('models', 'Models'), 'url' => [ 'index' ]];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="models-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'type_id',
            'modelnum',
            'product',
        ],
    ]) ?>

</div>