models/Site.php
<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * Эта модель используется для формирования сводныз данных на стартовой странице,
 * исполшьзуя данные из связанных аблиц ({%items}), {{%types}}, {{%locations}}, {{%regions}}/
 *
 * @property ActiveDataProvider|null regionsDataProvider Сводная таблица, содержащая количество оборудования по регионам
 * @property ActiveDataProvider|null typesDataProvider   Сводная таблица, содержащая количество оборудования по типам
 */

class Site extends \yii\data\ActiveDataProvider
{

    public static function regionsDataProvider()
    {

        $subQuery = Moving::find()
                ->select('MAX(id) AS id')
                ->distinct('item_id')
                ->groupBy(['item_id']);

        $query = Regions::find()
            ->select(Regions::tableName() . '.name, count(' . Items::tableName() . '.id) AS icount, count(c.tid) AS ccount')
            ->joinWith(['locations', 'moving', 'items'])
            ->leftJoin(['c' => Regions::find()
                    ->select(Regions::tableName() . '.id, ' . Items::tableName() . '.id AS tid')
                    ->joinWith(['locations', 'moving', 'items'])
                    ->where(['in', Moving::tableName() . '.id', $subQuery])
                    ->andWhere(Items::tableName() . '.checked = true')
                ], Regions::tableName() . '.id = c.id AND ' . Items::tableName() . '.id = c.tid')
            ->groupBy(Regions::tableName() . '.id')
            ->where(['in', Moving::tableName() . '.id', $subQuery]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        $dataProvider->setSort([
            'defaultOrder' => [
                'name' => SORT_ASC,
            ],
        ]);

        return $dataProvider;
    }

    public static function typesDataProvider()
    {

        $query = Types::find()
            ->select(Types::tableName() . '.name, count(' . Items::tableName() . '.id) AS icount, count( c.tid ) AS ccount')
            ->joinWith('items')
            ->leftJoin(['c' => Items::find()
                    ->select('id AS tid')
                    ->where(['checked' => true ])
                ], Items::tableName() . '.id = c.tid')
            ->groupBy(Types::tableName() . '.id');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);
        $dataProvider->setSort([
            'defaultOrder' => [
                'name' => SORT_ASC,
            ],
        ]);
        return $dataProvider;
    }
}

controllers/ItemsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Items;
use app\models\Import;
use app\models\Check;
use app\models\Moving;
use app\models\Locations;
use app\models\ItemsSearch;
use app\models\MovingSearch;
use app\models\Status;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;

use kartik\mpdf\Pdf;
use \phpexcel;

#require "/vendor/phpoffice/phpexcel/Classes/PHPExcel.php";

/**
 * ItemsController implements the CRUD actions for Items model.
 */
class ItemsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'POST' ],
                ],
            ],
        ];
    }

    /**
     * Добавление предмета/оборудование если его нет
     * @param array $options
     *        string 'invent'
     *        string 'model'
     *        string 'comment'
     *        integer|NULL 'type_id'
     *        string|NULL 'typeName'
     *        string|NULL 'name'
     *        string|NULL 'os'
     *        string|NULL 'mac'
     *        string|NULL 'serial'
     *        string|NULL 'product'
     *        string|NULL 'modelnum'
     * @return integer|FALSE
     */
    public static function addIfNeed($options)
    {
        // Если указан инвентарный номер
        if (is_array($options) && isset($options[ 'invent' ]))
        {
            $item = Items::find()
                ->where([ 'like', 'invent', $options[ 'invent' ]]); // Ищем оборудование с инвентарным номером.
            // Если указан серийный номер
            if (isset($options[ 'serial' ])) {
                $item = $item->andWhere([ 'like', 'serial', $options[ 'serial' ]]); // Ищем дополнительно с серийным номером
            }
            $item = $item->all(); // Получаем все записи

            if (count($item) > 0) // Записи найдены, выводим первую совпавшую
            {
                return $item[0]->id;
            }
            // Внесённого оборудования не найдено. Добавим новую запись
            if (isset($options[ 'model' ]))
            {
                // Если указан тип предмета/оборудования
                if (isset($options[ 'typeName' ]))
                {
                    $type_id = TypesController::addIfNeed($options[ 'typeName' ]); // Найдём или добавим тип
                    // Если тип не добавили
                    if($type_id === FALSE)
                    {
                        $type_id = NULL; // сделаем его пустым
                    }
                }
                else
                {
                    // Если указан идентификатор типа, укажем его
                    $type_id = isset($options[ 'type_id' ]) ? $options[ 'type_id' ] : NULL;
                }
                // Создаём новую запись предмета/оборудования
                $item = new Items();
                $item->name        = isset($options[ 'name' ]) ? $options[ 'name' ] : NULL;       // Сетевое имя
                $item->model       = isset($options[ 'model' ]) ? $options[ 'model' ] : NULL;     // Наименование
                $item->invent      = isset($options[ 'invent' ]) ? $options[ 'invent' ] : NULL;   // Инвентарный номер
                $item->comment     = isset($options[ 'comment' ]) ? $options[ 'comment' ] : NULL; // Коментарий
                $item->type_id     = $type_id;                                                    // Идентификатор типа
                $item->os          = isset($options[ 'os' ]) ? $options[ 'os' ] : NULL;           // Операционная система
                $item->mac         = isset($options[ 'mac' ]) ? $options[ 'mac' ] : NULL;         // MAC-адрес
                $item->serial      = isset($options[ 'serial' ]) ? $options[ 'serial' ] : NULL;   // Серийный номер
                $item->product     = isset($options[ 'product' ]) ? $options[ 'product' ] : NULL; // Код оборудования
                $item->modelnumber = isset($options[ 'modelnumber' ]) ? $options[ 'modelnumber' ] : NULL; // Номер модели
                $item->checked     = false;                                                       // Не инвентризирован (требует внимания после импорта)
                // Сохраняем запись
                if ($item->validate() && $item->save())
                {
                    return $item->id; // Возвращаем идентификатор записанного оборудования
                }
            }
        }
        return FALSE;
    }

    /**
     * Формирование PDF файла для печати QR-кодов для наклеек
     * @param integer|array|null id
     * @return mixed
     */
    public function actionPrint()
    {
        if (! User::canPermission('takingInventory') ) {
            return $this->redirect(['site/index']);
        }
        // Список предметов/оборудования, если есть
        $id = Yii::$app->request->get('id');

        $models = Items::find();
        if (isset($id))
            if (is_array($id))
            {
                $models = $models->where([ 'in', 'id', $id ]); // Несколько предметов/оборудования
            } else
            {
                $models = $models->where([ 'id' => $id ]); // Один предмет/оборудование
            }
        $models = $models->all(); // Формирование списка

        $pdf = Yii::$app->pdf; // Pабота с PDF

        $pdf->methods[ 'SetHeader' ] = ''; // Yii::t('items', 'Items');
        $pdf->methods[ 'SetFooter' ] = ''; // ['{PAGENO}'];
        // Границы листа
        $pdf->marginLeft   = 5;
        $pdf->marginRight  = 5;
        $pdf->marginTop    = 9;
        $pdf->marginBottom = 15;
        // Имя файла для выгрузки, по умолчанию document.pdf
        $pdf->filename     = Yii::t('app', Yii::$app->name) . ' (' . Yii::t('items', 'Items') . ').pdf';

        // Заполнение страницы данными
        $pdf->content = $this->renderPartial('print', [ 'models' => $models ]);

        // Выгрузка PDF
        return $pdf->render();
    }

    /**
     * Процедура начала инвентаризации.
     * @return mixed
     */
    public function actionStart_checking()
    {
        // Проверка доступа для проведения инвентаризации
        if (! User::canPermission('takingInventory') ) {
            // Переход к списку предметов/оборудования, если доступ не разрешён.
            return $this->redirect(['index']);
        }
        // Запрос на получение списка идентификаторов предметов/оборудования, которые списаны
        $modelS = Moving::find()
            ->select('item_id')
            ->joinWith('status')
            ->Where([ 'ilike', Status::tableName() . '.name', 'Списано' ]);

        // Получаем список всех предметов/оборудования, кроме списанного
        $model = Items::find()
            ->select('id')
            ->innerJoin([ 'm' => $modelS ], 'not m.item_id = id')
            ->all();

        // Устанавливаем флаг непроинвентаризированных для всех предметов/оборудования из полученного списка.
        Items::updateAll([ 'checked' => false ], [ 'in', 'id', $model ]);

        // Переход к списку предметов/оборудования.
        return $this->redirect([ 'index' ]);
    }

    /**
     * Инвентаризация
     * @param string|null $qrcheck считанный QR-код
     * @return mixed
     */
     public function actionCheck()
     {
        // Проверка доступа для проведения инвентаризации
        if (! User::canPermission('takingInventory') ) {
            // Показ стартовой страницы, если доступ не разрешён.
            return $this->redirect(['site/index']);
        }

        $model = new Check();
        $message = '';
        if ($model->load(Yii::$app->request->post()))
        {
            if ((! empty($model->qrcheck)) && strpos($model->qrcheck, ',') !== false)
            {
                $keys = explode(',', $model->qrcheck);
                Items::updateAll([ 'checked' => true ], [ 'invent' => trim($keys[ 0 ]), 'serial' => trim($keys[ 1 ]) ]);
                $items = Items::find()->where([ 'invent' => trim($keys[ 0 ]), 'serial' => trim($keys[ 1 ]) ])->all();
                //$message = '[0] = "' . $keys[0] . '", [1] = "' . $keys[1] . '"<br />';
                foreach ($items as $row)
                {
                    $message .= $row->model . ' (' . $row->id . ')';
                }
                if ($message != '')
                    $message = Yii::t('items', 'Checked item(s): ') . $message;
                $model->qrcheck = '';
            }
        }
        $searchModel = new ItemsSearch();
        $dataProvider = $searchModel->noinvent($model);

        return $this->render('check', [
            'message'      => $message,
            'model'        => $model,
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
     }

    /**
     * Список всех предметов/оборудования.
     * @return mixed
     */
    public function actionIndex()
    {
        if (! User::canPermission('createRecord') ) {
            return $this->redirect(['site/index']);
        }
        $searchModel = new ItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Импорт данных из файла csv
     * Структура файла данных при выгрузке из 1С:
     * | № п/п |  | Предмет/оборудование |  |  |  |  |  |  | Инвентарный номер | Материально отвественное лицо |  |  | Место размещения | Регион/подразделение | Количество |
     * | 0     | 1| 2                    | 3| 4| 5| 6| 7| 8| 9                 |10                             |11|12|13                |14                    |15          |
     * | A     | B| C                    | D| E| F| G| H| I| J                 | K                             | L| M| N                | O                    | P          |

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use app\models\Site;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => [ 'logout' ],
                'rules' => [
                    [
                        'actions' => [ 'logout' ],
                        'allow'   => true,
                        'roles'   => [ '@' ],
                    ],
                ],
            ],
            'verbs'    => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => [ 'post' ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Показ стартовой страницы.
     *
     * @return string
     */
    public function actionIndex()
    {

        return $this->render('index', [
            'dataProvider'      => Site::regionsDataProvider(),
            'dataProviderTypes' => Site::typesDataProvider(),
        ]);
    }

    /**
     * Вход пользователем.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest)
        {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login())
        {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Выход пользователем.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Поках страницы с обратной связью.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail']))
        {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Показ страницы описания.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('app', 'About');
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <div>
        Программа инвентаризации. <sub style="color:gray;">(Версия <?= Yii::$app->version ?>)</sub>
    </div>
    <div>Разработа для ведения учёта оборудования по подразделениям.</div>
    <div style="color:lightgray">По вопросам работы программы, обращайтесь к разработчику.</div>

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = Yii::t('contact', 'Contact');
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted'))
          { ?>

        <div class="alert alert-success">
            <?= Yii::t('contact', 'Thank you for contacting us. We will respond to you as soon as possible.') ?>
        </div>

        <p>
            <?= Yii::t('contact', 'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.') ?>
            <?php if (Yii::$app->mailer->useFileTransport)
                  { ?>
                <?= Yii::t('contact', 'Because the application is in development mode, the email is not sent but saved as a file under') ?> <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                <?= Yii::t('contact', 'Please configure the <code>useFileTransport</code> property of the <code>mail</code> application component to be false to enable email sending.') ?>
            <?php } ?>
        </p>

    <?php } else
          { ?>

        <p>
            <?= Yii::t('contact', 'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.') ?>
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin([ 'id' => 'contact-form' ]); ?>

                    <?= $form->field($model, 'name')->textInput([ 'autofocus' => true ]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea([ 'rows' => 6 ]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton(Yii::t('contact','Submit'), [ 'class' => 'btn btn-primary', 'name' => 'contact-button' ]) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php } ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        <?= Yii::t('app', 'The above error occurred while the Web server was processing your request.') ?>
    </p>
    <p>
        <?= Yii::t('app', 'Please contact us if you think this is a server error. Thank you.') ?>
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

use yii\data\SqlDataProvider;

use app\models\Regions;
use app\models\Locations;
use app\models\User;

/* @var $this yii\web\View */



$this->title = Yii::t('app',Yii::$app->name);
?>
<div class="site-index">

    <h2><?= Yii::t('app', 'Number of equipment by regions') ?></h2>
    <?= GridView::widget([
        'id' => 'RegionsTable',
        'dataProvider' => $dataProvider,
        'columns' => [
            'name',
            [ 'attribute' => 'icount',
                'contentOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
                'headerOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
            ],
            [ 'attribute' => 'ccount',
                'contentOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
                'headerOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
            ],
        ],
    ]);
    ?>

    <h2><?= Yii::t('app', 'Number of items by type') ?></h2>
    <?= GridView::widget([
        'id' => 'TypesTable',
        'dataProvider' => $dataProviderTypes,
        'columns' => [
            'name',
            [ 'attribute' => 'icount',
                'contentOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
                'headerOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
            ],
            [ 'attribute' => 'ccount',
                'contentOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
                'headerOptions' => [
                    'class' => 'text-center',
                    'style' => 'max-width:100px; width:100px;',
                ],
            ],
//            'icount',
//            'ccount',
        ],
    ]);
    // Подключение кнопки если есть права
    if ( User::canPermission('takingInventory') )
    {
    ?>

    <div class="row">
        <div class="col-md-3"><?= Html::a(Yii::t('app', 'Inventory'), [ 'items/check' ], [ 'class' => 'btn btn-info' ]) ?></div>
    </div>
    <?php
    }
    ?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Login');
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode(Yii::t('app', $this->title)) ?></h1>

    <p><?= Yii::t('app', 'Please fill out the following fields to login:') ?></p>

    <?php $form = ActiveForm::begin([
        'id'          => 'login-form',
        'layout'      => 'horizontal',
        'fieldConfig' => [
            'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => [ 'class' => 'col-lg-2 control-label' ],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput([ 'autofocus' => true ]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'Login'), [ 'class' => 'btn btn-primary', 'name' => 'login-button' ]) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        <?= Yii::t('app', 'You may login with') ?> <strong>admin/admin</strong> <?= Yii::t('app', 'or') ?> <strong>demo/demo</strong>.<br>
        <?= Yii::t('app', 'To modify the username/password, please check out the code') ?> <code>app\models\User::$users</code>.
    </div>
</div>