models/Items.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table 'items'.
 *
 * @property int $id                   Идентификатор (неизменяемый)
 * @property int $type_id              Идентификатор типа оборудования
 * @property string|null  $name         Сетевое имя оборудования
 * @property string|null  $model        Модель оборудования
 * @property string|null  $os           Операционная система
 * @property string|null  $mac          Сетевой MAC адрес
 * @property string|null  $serial       Серийный номер
 * @property string|null  $product      Код оборудования
 * @property string|null  $modelnumber  Номер модели
 * @property string|null  $invent       Инвентарный номер
 * @property boolean      $checked      Флаг прохождения инвентаризации
 * @property string|null  $statusName   Наименование состояния
 * @property string|null  $typeName     Наименование типа
 * @property string|null  $locationName Наименование места размещения
 * @property string|null  $regionName   Наименование региона/подразделения
 */
class Items extends \yii\db\ActiveRecord
{
    public $statusName;
    public $typeName;
    public $locationName;
    public $regionName;
    public $myMessage;
     /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%items}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'model', 'os', 'serial', 'product', 'modelnumber', 'comment' ], 'string', 'max' => 255],
            [['mac'],    'string', 'max' => 20],
            [['invent'], 'string', 'max' => 50],
            [['type_id'], 'integer'],
            [['checked'], 'boolean'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'           => Yii::t('app',   'Identifier'),              // Идентификатор
            'name'         => Yii::t('items', 'Item network name'),       // Сетевое имя оборудования
            'model'        => Yii::t('items', 'Model'),                   // Модель
            'os'           => Yii::t('items', 'Operating system'),        // Операционная система
            'mac'          => Yii::t('items', 'MAC address'),             // MAC адрес
            'serial'       => Yii::t('items', 'Serial number'),           // Серийный номер
            'product'      => Yii::t('items', 'Product number'),          // Номер продукции
            'modelnumber'  => Yii::t('items', 'Model number'),            // Номер модели
            'invent'       => Yii::t('items', 'Inventory number'),        // Инвентарный номер
            'comment'      => Yii::t('items', 'Additional Information'),  // Дополнительная информация
            'checked'      => Yii::t('items', 'Location checked'),        // Проинвентаризировано
            'statusName'   => Yii::t('items', 'State'),                   // Название состояния
            'type_id'      => Yii::t('items', 'Item type'),               // Идентификатор типа
            'typeName'     => Yii::t('items', 'Item type'),               // Название типа
            'locationName' => Yii::t('items', 'Location'),                // Название местоположения
            'regionName'   => Yii::t('items', 'Region'),                  // Название подразделения

        ];
    }

    // Получение типа предмета/оборудования
    public function getTypes()
    {
        return $this->hasOne(Types::className(), ['id' => 'type_id']);
    }

    // Получение всех перемещений предмета/оборудования
    public function getMoving()
    {
        return $this->hasMany(Moving::className(), ['item_id' => 'id']);
    }

    // Получение статусов предмета/оборудования
    public function getStatus()
    {
        return $this->getMoving()->select(Status::tableName() . '.*')->joinWith('status');
    }

    // Получение места размещения предмета/оборудования
    public function getLocations()
    {
        return $this->getMoving()->select(Locations::tableName() . '.*')->joinWith('locations');
    }

    // Получение Получение региона/подразделения размещения предмета/оборудования
    public function getRegions()
    {
        return $this->getLocations()->select(Regions::tableName() .'.*')->joinWith('regions');
    }

}

controllers/MovingController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Moving;
use app\models\MovingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;

/**
 * MovingController implements the CRUD actions for Moving model.
 */
class MovingController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'POST' ],
                ],
            ],
        ];
    }

    /**
     * Показ всех перемещений.
     * @return mixed
     */
    public function actionIndex()
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
         $searchModel  = new MovingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Показ одного перемещения (не используется).
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует перемещение
     */
    public function actionView($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Создание новго перемещения.
     * В случае успешного создания, происходит переход к конкретному оборудованию.
     * @return mixed
     */
    public function actionCreate($item_id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = new Moving();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'items/update', 'id' => $model->item_id ]);
        }

        $model->item_id = $item_id;
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Изменение перемещения.
     * В случае успешного изменения, происходит переход к конкретному оборудованию.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует перемещение
     */
    public function actionUpdate($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'items/update', 'id' => $model->item_id ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Удаление существующего перемещения.
     * В случае успешного удаления, происходит переход к редактированию предмета/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует перемещение
     */
    public function actionDelete($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model   = $this->findModel($id);
        $item_id = $model->item_id;
        $model->delete();

        return $this->redirect([ 'items/update', 'id' => $item_id ]);
    }

    /**
     * Finds the Moving model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Moving the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Moving::findOne($id)) !== null)
        {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/TypesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Types;
use app\models\TypesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;

/**
 * TypesController implements the CRUD actions for Types model.
 */
class TypesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => [ 'POST' ],
                ],
            ],
        ];
    }

    /**
     * Добавление типа, если необходимо
     * @param array $options
     *        string 'name' - наименование
     * @return integer|boolean - Идентификатор типа или FALSE в случае неудачи
     */
     public function addIfNeed($options)
     {
        if (is_array($options) && isset($options[ 'name' ]))
        {
            $type = Types::find()
                ->where([ 'like', 'name', $options[ 'name' ] ])
                ->all();
            if (count($type) > 0)
            {
                return $type[0]->id;
            }
            $type = new Types();
            $type->name = $options[ 'name' ];
            if ($type->validate() && $type->save())
            {
                return $type->id;
            }
        }
        return FALSE;
     }

    /**
     * Список всех типов предметов/оборудования.
     * @return mixed
     */
    public function actionIndex()
    {
        if (! User::canPermission('createRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $searchModel  = new TypesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Показ одного типа предмета/оборудования (не используется).
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionView($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['index']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Создание нового типа предмета/оборудования.
     * При успешном создании, происходит переход к списку всех типов предметов/оборудования.
     * @return mixed
     */
    public function actionCreate()
    {
        if (! User::canPermission('createRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = new Types();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'index', 'id' => $model->id ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Изменение существующего типа предмета/оборудования.
     * При успешном изменении, происходит переход к списку всех типов предметов/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionUpdate($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->redirect([ 'index', 'id' => $model->id ]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Удаление существующего типа предмета/оборудования.
     * При успешном удалении, происходит переход к списку всех типов предметов/оборудования.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException если отсутствует тип предмета/оборудования
     */
    public function actionDelete($id)
    {
        if (! User::canPermission('updateRecord'))
        {
            return $this->redirect(['site/index']);
        }
        $this->findModel($id)->delete();

        return $this->redirect([ 'index' ]);
    }

    /**
     * Finds the Types model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Types the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Types::findOne($id)) !== null)
        {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/items/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\jui\DatePicker;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Status;
use app\models\Types;
use app\models\Locations;
use app\models\Regions;

use xj\qrcode\QRcode;
use xj\qrcode\widgets\Email;
use xj\qrcode\widgets\Text;

use yii\data\Sort;

/* @var $this yii\web\View */
/* @var $model app\models\Items */
/* @var $form yii\widgets\ActiveForm */
//$this->registerJsFile("@web/js/regiondatepicker.js", ['depends' => [ \yii\web\JqueryAsset::className() ]] );

    // Создание сортированного списка для выбора типов оборудования
    $types = ArrayHelper::map(Types::find()->orderBy('name')->all(), 'id', 'name');

    if ($model->isNewRecord)
    {
        // Создание сортированного списка для выбора состояний оборудования
        $states = ArrayHelper::map(Status::find()->orderBy('name')->all(), 'id', 'name');
        $defState = [ 'options' => [Status::findOne([ 'name' => 'Склад' ])->id => [ 'Selected' => 'true' ] ]];

        // Создание сортированного списка для выбора расположения оборудования
        $locations = ArrayHelper::map(Locations::find()->joinWith('regions')->orderBy('name')->all(), 'id', 'name');
        foreach ($locations as $key => $val) {
            $locations[ $key ] = $val . ' (' .
                Regions::findOne(['id' => Locations::findOne(['id' => $key])->region_id])->name .
                ')';
        }
        // Значения по умолчанию для случая создания нового
        $defLocate = [ 'options' => [ 'empty' => [ 'Disabled' => 'true' ], Locations::findOne([ 'name' => 'Матвейково' ])->id => [ 'Selected' => 'true' ]] ];


        $modelm->date = date('d.m.Y'); // Текущая дата по умолчанию
    } else {
        // Показ QR-кода инвентаризации
        echo '<div style="border: lightgray;border-style: double;display: inline-table;padding: 5px;width: 400px;margin: 0 0 20px;border-radius: 15px;">'.
            '<div style="display:table-cell">' . Text::widget([
            'outputDir' => '@webroot/upload/qrcode',
            'outputDirWeb' => '@web/upload/qrcode',
            'text' => $model->invent . ', ' . $model->serial,
            'size' => 3,
            'margin' => 4,
            'ecLevel' => QRcode::QR_ECLEVEL_L,
        ]) . '</div><div style="display:table-cell;vertical-align:middle;font-size: 18pt;font-weight: bolder;text-align:center;">' . $model->invent . ', ' . $model->model .
        '</div></div>';
    }

?>


<div class="items-form">


    <?php $form = ActiveForm::begin([ 'id' => 'ItemForm' ]); ?>

    <?= $form->field($model,
            'type_id',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-5">{input}</div><div class="col-md-2">' .
                       Html::a(Yii::t('types', 'Types'), [ 'types/index' ], [ 'class' => 'btn btn-primary' ] ) .
                       '</div><div class="col-md-8">{error}</div></div>' ])
            ->dropDownList( $types, ['prompt' => Yii::t('types', 'Select type')] ) ?>

    <?= $form->field($model,
            'name',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model, 
            'model',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'os',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'mac',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'serial',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'product',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'modelnumber',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>

    <?= $form->field($model,
            'invent',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textInput([ 'maxlength' => true ]) ?>
    <?php
        // Если предмет/оборудование создаётся, то покажем поля даты, состояния, местоположения
        if ( isset($modelm))
        {
    ?>
        <?= $form->field( $modelm,
                'date',
                [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ] )
                ->widget(
                    DatePicker::className(),
                    [ 'language'   => 'ru',
                      'dateFormat' => 'dd.MM.yyyy',
                    ],
                ) ;
        ?>

        <?= $form->field($modelm,
                'state_id',
                [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-2">{input}</div><div class="col-md-8">{error}</div></div>' ])
                ->dropDownList($states, $defState)
                ->label(Yii::t('status', 'Status')) ?>

        <?= $form->field($modelm,
                'location_id',
                [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-5">{input}</div><div class="col-md-2">' .
                    Html::a(
                        Yii::t('locations', 'Locations'),
                        [ 'locations/index' ],
                        [ 'class' => 'btn btn-primary' ]
                    ) .
                    '</div><div class="col-md-8">{error}</div></div>' ])
                ->dropDownList($locations, $defLocate, ['prompt' => Yii::t('locations', 'Select location')])
                ->label(Yii::t('locations', 'Location')) ?>

    <?php
        }
    ?>
    <?= $form->field($model,
            'comment',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-7">{input}</div><div class="col-md-8">{error}</div></div>' ])
            ->textarea(['rows' => '10']) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'),   [ 'class' => 'btn btn-success' ]) ?>
        <?= Html::a(           Yii::t('app', 'Cancel'), [ 'index' ], [ 'class' => 'btn btn-primary' ]) ?>
    </div>


    <?php ActiveForm::end();

        // Если предмет/оборудование редактируется, то покажем все его движения
        if ( ! isset($modelm) )
        {

    ?>
        <H3><?= Yii::t('moving', 'Movings') ?></H3>

        <p>
            <?= Html::a(Yii::t('moving', 'Create Moving'), [ 'moving/create', 'item_id' => $model->id ], [ 'class' => 'btn btn-success' ]) ?>
        </p>

    <?php
            $GLOBALS['count'] = 0;
            echo GridView::widget([
                'id' => 'MovingTable',
                'dataProvider' => $dataProviderM,
                'filterModel' => $searchModelM,
                'columns' => [

//                    'id',
                    [ 'attribute' => 'date',
                        'value' => function($data)
                        {
                            return Html::a(Html::encode(Yii::$app->formatter->asDate($data->date, 'dd.MM.y')), [ 'moving/update', 'id' => $data->id ]);
                        },
                    'format' => 'raw',
                    ],
//                    'item_id',
                    [ 'attribute' => 'itemModel',
                        'value' => function($data)
                        {
                            return Html::a(Html::encode($data->items->invent . ' (' .$data->itemModel . ')'), [ 'moving/update', 'id' => $data->id ]);
                        },
                        'format' => 'raw',
                    ],

                    [ 'attribute' => 'locationName',
                        'value' => function($data)
                        {
                            return Html::a(Html::encode($data->locationName . ' (' .$data->regionName . ')'), [ 'moving/update', 'id' => $data->id ]);
                        },
                        'format' => 'raw',
                    ],

                    [ 'attribute' => 'statusName',
                        'value' => function($data)
                        {
                            return showUrlUpdate($data->statusName, $data);
                        },
                        'format' => 'raw',
                    ],
//                    'comment:ntext',

                    [ 'class' => 'yii\grid\ActionColumn',
                        'template' => '{delete}',
                        'buttons' => [
                            'delete' => function ($url, $model, $index)
                            {
                                if ($GLOBALS['count']++ != 0)
                                {
                                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', [ 'moving/delete', 'id' => $model->id ], 
                                        [ 'data' => [ 'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'), 'method' => 'post', ], ]);
                                } else { return ''; }
                            },
                        ],
                    ],
                ],
            ]);

        }
    ?>


</div>

views/items/_formimport.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\jui\DatePicker;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Status;
use app\models\Types;
use app\models\Locations;
use app\models\Regions;

use xj\qrcode\QRcode;
use xj\qrcode\widgets\Email;
use xj\qrcode\widgets\Text;

use yii\data\Sort;

/* @var $this yii\web\View */
/* @var $model app\models\Items */
/* @var $form yii\widgets\ActiveForm */

?>


<div class="items-form">


    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model,
            'filecsv',
            [ 'template' => '<div class="row"><div class="col-md-2">{label}</div><div class="col-md-5">{input}</div><div class="col-md-2">' .
                       '</div><div class="col-md-8">{error}</div></div>' ])
            ->fileInput([ 'accept' => '.csv,.xls,.xlsx' ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Import'),   [ 'class' => 'btn btn-success' ]) ?>
        <?= Html::a(           Yii::t('app', 'Cancel'), [ 'index' ], [ 'class' => 'btn btn-primary' ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/items/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ItemsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="items-search">

    <?php $form = ActiveForm::begin([
        'action' => [ 'index' ],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?php //= $form->field($model, 'id') 
    ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'model') ?>

    <?php //= $form->field($model, 'os') 
    ?>

    <?php //= $form->field($model, 'mac') 
    ?>

    <?= $form->field($model, 'serial') ?>

    <?php // echo $form->field($model, 'product'); 
    ?>

    <?php // echo $form->field($model, 'modelnumber'); 
    ?>

    <?= $form->field($model, 'invent') ?>

    <?= $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'comment'); 
    ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), [ 'class' => 'btn btn-primary' ]) ?>
        <?= Html::resetButton( Yii::t('app', 'Reset'),  [ 'class' => 'btn btn-outline-secondary' ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/items/create.php
<?php

use yii\helpers\Html;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Items */

if (! User::canPermission('createRecord'))
{
    return $this->redirect(['site/index']);
}
$this->title = Yii::t('items', 'Create Items');
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('app', 'Items'), 'url' => [ 'index' ]];
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="items-create">

     <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelm' => $modelm,
    ]) ?>

</div>

views/items/import.php
<?php

use yii\helpers\Html;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Items */

if (! User::canPermission('updateRecord'))
{
    return $this->redirect(['site/index']);
}

$this->title = Yii::t('items', 'Import Items');
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('app', 'Items'), 'url' => [ 'index' ]];
$this->params[ 'breadcrumbs' ][] = $this->title;
?>
<div class="items-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $message ?>
    </p>
    <?= $this->render('_formimport', [
        'model' => $model,
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
    ]) ?>

</div>

views/items/print.php
<?php

use yii\helpers\Html;
use app\models\Items;
use app\models\Types;
use app\models\User;

use xj\qrcode\QRcode;
use xj\qrcode\widgets\Email;
use xj\qrcode\widgets\Text;

if (! User::canPermission('updateRecord'))
{
    return $this->redirect(['site/index']);
}

$this->title = Yii::t('items', 'Items');
$this->params[ 'breadcrumbs' ][] = $this->title;

?>
<div class="items-index">

    <table width="100%">
        <tbody>
            <?php
                $counts = 3;
                $percent = (100 / $counts) % 100;
                $ind = 0;
                foreach ($models as $model )
                {
            ?>

                <?php
                    if ($ind % $counts == 0)
                    {
                        echo '<tr style="height:120px;min-height:120px;max-height:120px;">';
                    }
                    $ind++;
                ?>
                <td style="width:<?= $percent ?>%;">
                    <div style="margin:2px 2px 2px 2px;border-color:black;border-width:4,4;border-style:double;border-radius:15px;height:94%;width:98%">
                        <table width="100%" height="100%">
                            <tbody>
                                <tr>
                                    <td style="vertical-align:middle;">
                                        <?= Text::widget([
                                            'outputDir'    => '@webroot/upload/qrcode',
                                            'outputDirWeb' => '@web/upload/qrcode',
                                            'text'         => $model->invent . ', ' . $model->serial,
                                            'size'         => 3,
                                            'margin'       => 4,
                                            'ecLevel'      => QRcode::QR_ECLEVEL_L,
                                        ]) ?>
                                    </td>
                                    <td style="vertical-align:middle;">
                                        <?= $model->invent . ', ' . $model->model ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </td>
                <?php
                    if ($ind % $counts == 0)
                    {
                        echo '</tr>';
                    }
                }
                if ($ind % $counts != 0)
                {
                    while ($ind % $counts != 0)
                    {
                        echo '<td>&nbsp;</td>';
                        $ind++;
                    }
                    echo '</tr>';
                }
            ?>
        </tbody>
    </table>
</div>

views/items/update.php
<?php

use yii\helpers\Html;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Items */

if (! User::canPermission('updateRecord'))
{
    return $this->redirect(['site/index']);
}

$this->title = Yii::t('items', 'Update Items: {name}', [
    'name' => $model->invent,
]);
$this->params[ 'breadcrumbs' ][] = [ 'label' => Yii::t('app', 'Items'), 'url' => [ 'index' ]];
$this->params[ 'breadcrumbs' ][] = Yii::t('app', 'Update');
?>
<div class="items-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'searchModelM' => $searchModelM,
        'dataProviderM' => $dataProviderM,
        'model' => $model,
    ]) ?>

</div>